name: docs
on: 
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: fastdotai/fastai
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.DH_HOSTS }}

    - name: Install libraries
      run: pip install -Uqqq nbdev "sentencepiece<0.1.90" wandb tensorboard albumentations pydicom opencv-python scikit-image pyarrow kornia

    - name: checkout contents of PR
      uses: actions/checkout@v2

    - name: Create docs
      id: docs
      run: |
        nbdev_build_docs
        cd docs
        JEKYLL_ENV=production bundle exec jekyll build
        rsync -az _site/* ps625762.dreamhostps.com:docs1.fast.ai
