name: docs
on: 
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: fastdotai/fastai
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.DH_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - name: Install libraries
      run: |
        pip install -Uqqq nbdev "sentencepiece<0.1.90" wandb tensorboard albumentations pydicom opencv-python scikit-image pyarrow kornia pytorch-lightning catalyst pytorch-ignite captum
        apt-get update && apt-get install -y rsync

    - name: checkout contents of PR
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create docs
      id: docs
      run: nbdev_build_docs

    - name: setup directories for Jekyll build
      run: |
        rm -rf docs/_site
        chmod -R 777 docs/

    - name: Jekyll build
      uses: docker://jekyll/jekyll:4.0.1
      with:
        args: bash -c "cd docs && gem install bundler && chmod -R u+rwx . && jekyll build -V --strict_front_matter --trace"
      env:
        JEKYLL_ENV: 'production'
    
    - name: rsync
      run: rsync  -e "ssh -l jeremyphoward -o StrictHostKeyChecking=no" -az docs/_site/ ps625762.dreamhostps.com:docs1.fast.ai/
