name: docs
on: 
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: fastdotai/fastai
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.DH_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }} # ssh_config; optional

    - name: Install libraries
      run: |
        pip install -Uqqq nbdev
    - name: Attempt to read notebooks
      run: |
        nbdev_read_nbs
    - name: Create docs
      id: docs
      run: |
        nbdev_build_docs
