name: docs
on: 
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.DH_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }} # ssh_config; optional
